### ISSUE TITLE
Background items are not dimmed when Finder windows are focused

### ISSUE THREAD

**Issue by lucasmezencio** [dwarvesf/blurred#12]
### Describe the bug

The app works perfectly with any app window that is not a "Finder" window. However, it doesn't work if you open a Finder window.

### Steps to reproduce

1. Open the app
2. Open any app window which is not the Finder window
3. The background items are dimmed (screenshots 1 and 2)
4. Open any Finder window
5. Background items are not dimmed anymore (screenshot 3)

### Expected behaviour

The background items should be always dimmed.

**Screenshots**

Screenshot 1
![image](https://user-images.githubusercontent.com/472412/86034192-67c42a00-ba3a-11ea-88c6-c0f72215f616.png)

Screenshot 2
![image](https://user-images.githubusercontent.com/472412/86034235-7d395400-ba3a-11ea-9828-a682f1e68367.png)

Screenshot 3
![image](https://user-images.githubusercontent.com/472412/86034266-8e826080-ba3a-11ea-911a-cb9b4b497366.png)

### Environment

![image](https://user-images.githubusercontent.com/472412/86034578-2a13d100-ba3b-11ea-9f1b-e4d4b31220fb.png)

![image](https://user-images.githubusercontent.com/472412/86034868-a6a6af80-ba3b-11ea-879d-3996a96a1edf.png)

**Comment by phucledien** [comment]
Hi @lucasmezencio, thank you for using our app and raising the issue 👍 

🤣 , it's our intent to not blur the finder window. The main reason is that we want when the user clicks to the desktop it will remove the blur. But as a side effect, it will also affect the Finder window 🤦 .

anw, after considering, I think it's not necessary anymore to keep this since I believe the finder is more important 😄 

So, I will fix this and release a new version soon. Thank you again for giving us feedback ❤️

**Comment by viettrungphan** [comment]
After discussions and consideration between Finder Dimming and Click on Desktop to see desktop contents we decided to keep the current behavior. Thanks for your understanding.
