### ISSUE TITLE
Why limit the blur to 10% intervals?

### ISSUE THREAD

**Issue by dsernst** [dwarvesf/blurred#7]
Is it necessary to limit the blur strength to 10% intervals?

I'm looking to set it a bit stronger than 90%, but not 100%. I think 95% may be what I'm looking for, or maybe 97% or 98%, but just unclear if it's helpful or necessary to limit the selection to these preset 10% intervals in the first place.

It's a cool little utility, btw 👍👍 Thanks for creating and sharing it.

**Comment by viettrungphan** [comment]
More than 90% make it hard to see contents behind it, for under 10% it not different from disabling dimming mode. I personally refer you to disable dimming because it better in terms of performance, the app doesn't have watch windows and insert Dimming window which is wasted since it was nearly transparent.
